# Generated by Django 5.1.4 on 2025-11-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_documentotipo_pais_region_usuariotipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='region',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(db_column='NOMBRE_USUARIO', default='usuario_temp', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='ID_PERSONA', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, db_column='NOMBRES', max_length=50)),
                ('apellidos', models.CharField(blank=True, db_column='APELLIDOS', max_length=50)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=100)),
                ('pais', models.ForeignKey(blank=True, db_column='ID_PAIS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais')),
                ('region', models.ForeignKey(blank=True, db_column='ID_REGION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region')),
                ('usuario', models.OneToOneField(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
