# Generated by Django 5.2.7 on 2025-11-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_documento_options_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento recibido',
                'verbose_name_plural': 'Eventos recibidos',
            },
        ),
    ]
