# Generated by Django 5.2.7 on 2025-11-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_eventolog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventolog',
            options={},
        ),
        migrations.RenameField(
            model_name='eventolog',
            old_name='evento',
            new_name='mensaje',
        ),
        migrations.AddField(
            model_name='eventolog',
            name='tipo',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
    ]
